site_name: Modelowanie 3D w Blenderze
copyright: 2025 Szymon Zadworny, Koło Naukowe Vertex PG
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/sajmon170

nav:
  - Strona domowa: index.md
  - Przygotowanie środowiska:
    - Konfiguracja Blendera: env/config.md
  - Kurs:
    - Wstęp - blockout: course/blockout.md
    - Box modeling - podstawy: course/box-modeling.md 

theme:
  logo: assets/logo_white_bold.png
  name: material
  language: pl

  features:
    - navigation.footer
  
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
